import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../../..');
const logoPath = path.resolve(repoRoot, 'client', 'src', 'assets', 'images', 'logo.png');

const loadLogo = () => {
  try {
    if (fs.existsSync(logoPath)) {
      return logoPath;
    }
  } catch (error) {
    console.warn('Logo not found for PDF reports:', error.message);
  }
  return null;
};

const logo = loadLogo();

const formatDateTime = (value) => {
  if (!value) return 'TBD';
  try {
    return new Date(value).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    });
  } catch {
    return 'TBD';
  }
};

const formatStatusNotes = (booking) => {
  const status = booking.status ? booking.status.toUpperCase() : 'PENDING';
  const venue = booking.venue ? `@ ${booking.venue}` : '';
  const note = booking.notes || booking.internalNote || '';
  return [status, venue, note].filter(Boolean).join(' • ');
};

export const createPdfId = () =>
  `PDF-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;

// Updated column definitions with better proportions
const columns = [
  { key: 'customer', label: 'Customer', width: 160, align: 'left' },
  { key: 'date', label: 'Date & Time', width: 130, align: 'left' },
  { key: 'service', label: 'Product/Service', width: 180, align: 'left' },
  { key: 'status', label: 'Status & Notes', width: 250, align: 'left' },
];

const COLORS = {
  primary: '#1E293B',
  secondary: '#475569',
  border: '#CBD5E1',
  headerBg: '#334155',
  rowEven: '#F8FAFC',
  rowOdd: '#FFFFFF',
  text: '#0F172A',
  textLight: '#64748B',
};

const drawHeader = (doc, { title, subtitle, pdfId, generatedBy }) => {
  const pageWidth = doc.page.width;
  const marginLeft = doc.page.margins.left;
  const marginRight = doc.page.margins.right;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let cursorY = doc.page.margins.top;

  // Logo section
  if (logo) {
    const logoWidth = 60;
    const logoX = pageWidth / 2 - logoWidth / 2;
    doc.image(logo, logoX, cursorY, { width: logoWidth });
    cursorY += 65;
  } else {
    cursorY += 10;
  }

  // Metadata section
  const metaY = cursorY;
  doc
    .fontSize(8)
    .fillColor(COLORS.secondary)
    .text(
      `Generated: ${new Date().toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })}`,
      marginLeft,
      metaY,
      {
        width: contentWidth / 2 - 10,
        align: 'left',
      }
    );

  doc.text(`Report ID: ${pdfId}`, marginLeft + contentWidth / 2 + 10, metaY, {
    width: contentWidth / 2 - 10,
    align: 'right',
  });

  cursorY += 16;

  if (generatedBy) {
    doc
      .fontSize(8)
      .fillColor(COLORS.secondary)
      .text(`Generated by: ${generatedBy}`, marginLeft, cursorY, {
        width: contentWidth,
        align: 'left',
      });
    cursorY += 18;
  } else {
    cursorY += 8;
  }

  // Title section
  doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold').text(title, marginLeft, cursorY, {
    width: contentWidth,
    align: 'center',
  });
  cursorY += 28;

  if (subtitle) {
    doc
      .fontSize(11)
      .fillColor(COLORS.secondary)
      .font('Helvetica')
      .text(subtitle, marginLeft, cursorY, {
        width: contentWidth,
        align: 'center',
      });
    cursorY += 22;
  } else {
    cursorY += 10;
  }

  // Divider line
  doc
    .strokeColor(COLORS.border)
    .lineWidth(1.5)
    .moveTo(marginLeft, cursorY)
    .lineTo(marginLeft + contentWidth, cursorY)
    .stroke();

  doc.y = cursorY + 20;
};

const drawTableHeader = (doc) => {
  const startX = doc.page.margins.left;
  const totalWidth = columns.reduce((sum, col) => sum + col.width, 0);
  let currentX = startX;

  // Draw header background
  doc.rect(startX, doc.y, totalWidth, 28).fillAndStroke(COLORS.headerBg, COLORS.border);

  // Draw header text with proper vertical centering
  const textY = doc.y + 9; // Center text vertically in 28px height

  columns.forEach((column) => {
    doc
      .fontSize(9)
      .fillColor('#FFFFFF')
      .font('Helvetica-Bold')
      .text(column.label.toUpperCase(), currentX + 10, textY, {
        width: column.width - 20,
        align: column.align || 'left',
        lineBreak: false,
      });
    currentX += column.width;
  });

  doc.y += 28;
  doc.font('Helvetica'); // Reset font
};

const drawTableRows = (doc, bookings, options) => {
  const startX = doc.page.margins.left;
  const totalWidth = columns.reduce((sum, col) => sum + col.width, 0);
  const bottomLimit = doc.page.height - doc.page.margins.bottom - 60;
  const maxRowsPerPage = options.rowsPerPage || 10;

  let rowsOnPage = 0;
  let totalRows = 0;

  const startNewPage = () => {
    doc.addPage();
    drawHeader(doc, options);
    drawTableHeader(doc);
    rowsOnPage = 0;
  };

  bookings.forEach((booking) => {
    const rowData = {
      customer: booking.user?.fullName || booking.user?.id?.fullName || 'Unknown Client',
      date: formatDateTime(booking.weddingDate),
      service:
        booking.package?.name ||
        (booking.externalSupplierSelections?.length ? 'Custom Package' : 'Pending Assignment'),
      status: formatStatusNotes(booking),
    };

    // Calculate required row height based on content
    const cellHeights = columns.map((column) => {
      const text = String(rowData[column.key] || '');
      return doc.heightOfString(text, {
        width: column.width - 20,
        align: column.align || 'left',
      });
    });

    const contentHeight = Math.max(...cellHeights);
    const rowHeight = Math.max(contentHeight + 16, 32); // Min height 32px with padding

    // Check if we need a new page
    if (rowsOnPage >= maxRowsPerPage || doc.y + rowHeight > bottomLimit) {
      startNewPage();
    }

    const rowY = doc.y;
    const backgroundColor = totalRows % 2 === 0 ? COLORS.rowEven : COLORS.rowOdd;

    // Draw row background with borders
    doc.rect(startX, rowY, totalWidth, rowHeight).fillAndStroke(backgroundColor, COLORS.border);

    // Draw cell content with proper vertical alignment
    let currentX = startX;
    const textY = rowY + 8; // Top padding for text

    columns.forEach((column) => {
      const cellText = String(rowData[column.key] || '');

      // Draw vertical cell borders
      if (currentX > startX) {
        doc
          .strokeColor(COLORS.border)
          .lineWidth(0.5)
          .moveTo(currentX, rowY)
          .lineTo(currentX, rowY + rowHeight)
          .stroke();
      }

      // Draw text content
      doc
        .fontSize(9)
        .fillColor(COLORS.text)
        .text(cellText, currentX + 10, textY, {
          width: column.width - 20,
          align: column.align || 'left',
          height: rowHeight - 16,
          ellipsis: true,
        });

      currentX += column.width;
    });

    doc.y = rowY + rowHeight;
    rowsOnPage += 1;
    totalRows += 1;
  });

  // Draw bottom border of last row
  const finalY = doc.y;
  doc
    .strokeColor(COLORS.border)
    .lineWidth(1.5)
    .moveTo(startX, finalY)
    .lineTo(startX + totalWidth, finalY)
    .stroke();
};

const drawFooter = (doc) => {
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;
  const marginLeft = doc.page.margins.left;
  const marginRight = doc.page.margins.right;
  const contentWidth = pageWidth - marginLeft - marginRight;
  const footerY = pageHeight - doc.page.margins.bottom + 20;

  doc
    .fontSize(8)
    .fillColor(COLORS.textLight)
    .text(`Page ${doc.bufferedPageRange().start + 1}`, marginLeft, footerY, {
      width: contentWidth,
      align: 'center',
    });
};

export const streamBookingsPdf = ({
  bookings = [],
  res,
  title = 'Bookings Overview',
  subtitle = '',
  generatedBy = 'System',
  pdfId = createPdfId(),
  rowsPerPage = 10,
}) => {
  const doc = new PDFDocument({
    margin: 50,
    size: 'A4',
    layout: 'landscape',
    bufferPages: true,
  });

  doc.pipe(res);

  // Draw initial header and table
  drawHeader(doc, { title, subtitle, pdfId, generatedBy });
  drawTableHeader(doc);

  if (bookings.length === 0) {
    doc
      .fontSize(11)
      .fillColor(COLORS.secondary)
      .text('No bookings found for the selected criteria.', doc.page.margins.left, doc.y + 30, {
        align: 'center',
      });
  } else {
    drawTableRows(doc, bookings, { title, subtitle, pdfId, generatedBy, rowsPerPage });
  }

  // Add page numbers to all pages
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    drawFooter(doc);
  }

  doc.end();

  return pdfId;
};
